/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardPanel = new javax.swing.JPanel();
        car_0_0 = new javax.swing.JLabel();
        car_0_1 = new javax.swing.JLabel();
        car_0_2 = new javax.swing.JLabel();
        car_1_0 = new javax.swing.JLabel();
        car_1_1 = new javax.swing.JLabel();
        car_1_2 = new javax.swing.JLabel();
        car_2_0 = new javax.swing.JLabel();
        car_2_1 = new javax.swing.JLabel();
        car_2_2 = new javax.swing.JLabel();
        car_3_0 = new javax.swing.JLabel();
        car_3_1 = new javax.swing.JLabel();
        car_3_2 = new javax.swing.JLabel();
        car_4_0 = new javax.swing.JLabel();
        car_4_1 = new javax.swing.JLabel();
        car_4_2 = new javax.swing.JLabel();
        car_5_0 = new javax.swing.JLabel();
        car_5_2 = new javax.swing.JLabel();
        car_5_1 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        boardLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        boardPanel.setBackground(new java.awt.Color(255, 255, 255));
        boardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        car_0_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_0_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 22, -1, -1));

        car_0_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_0_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 22, -1, -1));

        car_0_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_0_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 22, -1, -1));

        car_1_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_1_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 77, -1, -1));

        car_1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 77, -1, -1));

        car_1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 77, -1, -1));

        car_2_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_2_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 132, -1, -1));

        car_2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 132, -1, -1));

        car_2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 132, -1, -1));

        car_3_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_3_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 187, -1, -1));

        car_3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 187, -1, -1));

        car_3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 187, -1, -1));

        car_4_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_4_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 242, -1, -1));

        car_4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 242, -1, -1));

        car_4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-2.png"))); // NOI18N
        boardPanel.add(car_4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 242, -1, -1));

        car_5_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-green-1.png"))); // NOI18N
        boardPanel.add(car_5_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 319, -1, -1));

        car_5_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-green-1.png"))); // NOI18N
        boardPanel.add(car_5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 319, -1, -1));

        car_5_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/pixel-car-racer-pixel-art-8-bit-green-1.png"))); // NOI18N
        boardPanel.add(car_5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 319, -1, -1));

        scoreLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        boardLabel.setBackground(new java.awt.Color(255, 255, 255));
        boardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boardLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(boardLabel)
                .addGap(20, 20, 20)
                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public JLabel getBoardLabel() {
        return boardLabel;
    }

    public void setBoardLabel(JLabel boardLabel) {
        this.boardLabel = boardLabel;
    }

    public JPanel getBoardPanel() {
        return boardPanel;
    }

    public void setBoardPanel(JPanel boardPanel) {
        this.boardPanel = boardPanel;
    }

    public JLabel getScoreLabel() {
        return scoreLabel;
    }

    public void setScoreLabel(JLabel scoreLabel) {
        this.scoreLabel = scoreLabel;
    }

    public JLabel getCar_0_0() {
        return car_0_0;
    }

    public void setCar_0_0(JLabel car_0_0) {
        this.car_0_0 = car_0_0;
    }

    public JLabel getCar_0_1() {
        return car_0_1;
    }

    public void setCar_0_1(JLabel car_0_1) {
        this.car_0_1 = car_0_1;
    }

    public JLabel getCar_0_2() {
        return car_0_2;
    }

    public void setCar_0_2(JLabel car_0_2) {
        this.car_0_2 = car_0_2;
    }

    public JLabel getCar_1_0() {
        return car_1_0;
    }

    public void setCar_1_0(JLabel car_1_0) {
        this.car_1_0 = car_1_0;
    }

    public JLabel getCar_1_1() {
        return car_1_1;
    }

    public void setCar_1_1(JLabel car_1_1) {
        this.car_1_1 = car_1_1;
    }

    public JLabel getCar_1_2() {
        return car_1_2;
    }

    public void setCar_1_2(JLabel car_1_2) {
        this.car_1_2 = car_1_2;
    }

    public JLabel getCar_2_0() {
        return car_2_0;
    }

    public void setCar_2_0(JLabel car_2_0) {
        this.car_2_0 = car_2_0;
    }

    public JLabel getCar_2_1() {
        return car_2_1;
    }

    public void setCar_2_1(JLabel car_2_1) {
        this.car_2_1 = car_2_1;
    }

    public JLabel getCar_2_2() {
        return car_2_2;
    }

    public void setCar_2_2(JLabel car_2_2) {
        this.car_2_2 = car_2_2;
    }

    public JLabel getCar_3_0() {
        return car_3_0;
    }

    public void setCar_3_0(JLabel car_3_0) {
        this.car_3_0 = car_3_0;
    }

    public JLabel getCar_3_1() {
        return car_3_1;
    }

    public void setCar_3_1(JLabel car_3_1) {
        this.car_3_1 = car_3_1;
    }

    public JLabel getCar_3_2() {
        return car_3_2;
    }

    public void setCar_3_2(JLabel car_3_2) {
        this.car_3_2 = car_3_2;
    }

    public JLabel getCar_4_0() {
        return car_4_0;
    }

    public void setCar_4_0(JLabel car_4_0) {
        this.car_4_0 = car_4_0;
    }

    public JLabel getCar_4_1() {
        return car_4_1;
    }

    public void setCar_4_1(JLabel car_4_1) {
        this.car_4_1 = car_4_1;
    }

    public JLabel getCar_4_2() {
        return car_4_2;
    }

    public void setCar_4_2(JLabel car_4_2) {
        this.car_4_2 = car_4_2;
    }

    public JLabel getCar_5_0() {
        return car_5_0;
    }

    public void setCar_5_0(JLabel car_5_0) {
        this.car_5_0 = car_5_0;
    }

    public JLabel getCar_5_1() {
        return car_5_1;
    }

    public void setCar_5_1(JLabel car_5_1) {
        this.car_5_1 = car_5_1;
    }

    public JLabel getCar_5_2() {
        return car_5_2;
    }

    public void setCar_5_2(JLabel car_5_2) {
        this.car_5_2 = car_5_2;
    }

    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boardLabel;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JLabel car_0_0;
    private javax.swing.JLabel car_0_1;
    private javax.swing.JLabel car_0_2;
    private javax.swing.JLabel car_1_0;
    private javax.swing.JLabel car_1_1;
    private javax.swing.JLabel car_1_2;
    private javax.swing.JLabel car_2_0;
    private javax.swing.JLabel car_2_1;
    private javax.swing.JLabel car_2_2;
    private javax.swing.JLabel car_3_0;
    private javax.swing.JLabel car_3_1;
    private javax.swing.JLabel car_3_2;
    private javax.swing.JLabel car_4_0;
    private javax.swing.JLabel car_4_1;
    private javax.swing.JLabel car_4_2;
    private javax.swing.JLabel car_5_0;
    private javax.swing.JLabel car_5_1;
    private javax.swing.JLabel car_5_2;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}